apiVersion: v1
kind: PersistentVolume
metadata:
  name: atlantis-pv
  labels:
    app: atlantis
    release: atlantis
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv
