all:
  hosts:
    cp1:
      ansible_host: 192.168.10.3
      ansible_connection: ssh
      ansible_user: ubuntu
    node1:
      ansible_host: 192.168.10.10
      ansible_connection: ssh
      ansible_user: ubuntu
    node2:
      ansible_host: 192.168.20.21
      ansible_connection: ssh
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
