---
- name: Create config dir
  become: true
  file:
    path: /var/lib/jenkins/.kube
    owner: jenkins
    group: jenkins
    mode: 0755
    state: directory

- name: Copy Kubeconfig to Jenkins host
  become: true
  copy:
    src: /tmp/kubeconfig
    dest: /var/lib/jenkins/.kube/config
    owner: jenkins
    group: jenkins
    mode: 0640
