---
- name: Install Docker
  become: true
  shell: curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh

- name: group for Docker
  group:
    name: docker
    state: present

- name: add user to Docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
