---
#- name: Prepare Kubectl and CSR
#  hosts: jenkins
#  tasks:
#  - import_role:
#      name: prepare-kubectl
- name: Sign cert and create Kubeconfig
  hosts: cp1
  tasks:
  - import_role:
      name: new_cert_kubeconfig





