apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: unix:////var/run/containerd/containerd.sock
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
imageRepository: registry.k8s.io
kubernetesVersion: v1.24.3
etcd:
  external:
      endpoints:
      - https://192.168.10.3:2379
dns:
  type: CoreDNS
  imageRepository: registry.k8s.io/coredns
  imageTag: v1.8.6
